### ISSUE TITLE
virtual entities 

### ISSUE THREAD

**Issue by irugina** [dmurfet/2simplicialtransformer#1]
Hello, 

My apologies for what is probably a trivial question. I was wondering in the simplicial attention layers, according to your ICLR paper you are generating M or NUM_VIRTUAL_ENTITIES additional tokens. However, to me it seems that here:

https://github.com/dmurfet/2simplicialtransformer/blob/master/agent/agent_simplicial.py#L242

you are partitioning your sequence into (N-M, M) tokens rather than (N,M). 

Could you please clarify what I'm missing? 

Thank you!

**Comment by dmurfet** [comment]
It's a pleasure to find someone reading the code!

I think what you're missing is 

https://github.com/dmurfet/2simplicialtransformer/blob/d75630a5238c57b22e816e843584cf45284246d8/agent/agent_simplicial.py#L381 

where the virtual entities are concatenated onto the end of the list of entities. As a result x has dimensions (..., N+M, d_model) where N is the number of standard entities and M is the number of virtual entities. Hence at the line you mention, seq_len - num_ve = (N+M) - M = N.

Hope that helps.

Daniel.

**Comment by irugina** [comment]
Thank you!
